---
variables:
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
  PACKER_VERSION: 1.11.2

default:
  tags:
    - docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - test
  - build
  - test-image
  - deploy

build:
  stage: build
  tags:
    - shell
  script:
    - docker build --build-arg PACKER_BINARY_VERSION=$PACKER_VERSION --build-arg ARGOCD_BINARY_VERSION=$ARGOCD_VERSION --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test-image:
  stage: test-image
  tags:
    - shell
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE sh -c "packer --version"

release:
  stage: deploy
  tags:
    - shell
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - main
