---
- name: Enable kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Persist kernel modules
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s-modules.conf
    src: k8s-modules.conf
    owner: root
    group: root
    mode: "0644"

- name: Enable kubernetes generic sysctl params
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s-sysctl.conf
    src: k8s-sysctl.conf
    owner: root
    group: root
    mode: "0644"

- name: Disable swap 1/2
  ansible.builtin.shell: /usr/sbin/swapoff -a

- name: Disable swap 2/2
  ansible.builtin.shell: /usr/bin/sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: Create etcd group
  ansible.builtin.group:
    name: etcd
    state: present

- name: Create etcd user
  ansible.builtin.user:
    name: etcd
    group: etcd
    groups: etcd
    shell: /sbin/nologin
    comment: rke2 etcd user
    create_home: false
    state: present

- name: Download rke2 install skript
  ansible.builtin.get_url:
    url: https://get.rke2.io
    dest: /tmp/install_rke2.sh
    mode: "0700"
    owner: root
    group: root

- name: Create rke2 config dir
  ansible.builtin.file:
    path: /etc/rancher/rke2/
    state: directory
    mode: "0750"
    owner: root
    group: root

- name: Deploy rke2 config file
  ansible.builtin.template:
    src: rke2_config.yaml.j2
    dest: /etc/rancher/rke2/config.yaml
    mode: "0640"
    owner: root
    group: root

- name: Run rke2 install skript
  ansible.builtin.shell: INSTALL_RKE2_TYPE="server" INSTALL_RKE2_CHANNEL="stable" /tmp/install_rke2.sh
  args:
    creates: /etc/rancher/rke2/rke2.yaml

- name: Enable rke2 sysctl params
  ansible.builtin.copy:
    dest: /etc/sysctl.d/60-rke2-cis.conf
    src: /usr/local/share/rke2/rke2-cis-sysctl.conf
    owner: root
    group: root
    mode: "0644"
    remote_src: true

- name: Apply sysctl params
  ansible.builtin.shell: /usr/sbin/sysctl --system

- name: Start and enable rke2 server
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: true
    daemon_reload: true
  throttle: 1

- name: Ensure .kube
  ansible.builtin.file:
    path: ~/.kube
    state: directory
  delegate_to: localhost
  become: false

- name: Get kubeconfig
  ansible.builtin.fetch:
    src: "/etc/rancher/rke2/rke2.yaml"
    dest: "~/.kube/{{ cluster_name }}"
    flat: true
  when: ansible_hostname == primary_hostname

- name: Replace localhost
  ansible.builtin.replace:
    path: "~/.kube/{{ cluster_name }}"
    regexp: '127(?:\.[0-9]{0,3}){3}'
    replace: "{{ rke2_fqdn }}"
  delegate_to: localhost
  become: false

- name: Change permissions
  ansible.builtin.file:
    path: "~/.kube/{{ cluster_name }}"
    mode: "0600"
    state: file
  delegate_to: localhost
  become: false
